apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mirarifhasan/nestjs-cicd.git
    targetRevision: HEAD
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: new_namespace
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
