name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test: 
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     
     - name: Setup Node.js environment
       uses: actions/setup-node@v3.6.0
       
     - name: Check Node Version
       run: node -v
              
     - name: File list
       run: ls
       
     - name: Check Node Version
       run: npm install

     - name: Test NestJS Project
       run: npm run test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag health-service:$(date +%s)

    - name: Docker all images
      run: docker image ls
